development:
  adapter: mysql2
  database: openmrs
  host: 192.168.13.100
  username: root
  password: password
  pool: 500
  
production:
  adapter: mysql2
  database: data_migrator_test
  host: localhost
  username: root
  password: password
  pool: 500

openmrs_development:
  adapter: mysql2
  database: openmrs
  host: 192.168.13.100
  username: root
  password: password
  pool: 500
